### ISSUE TITLE
Error on parsing payment operation's response

### ISSUE THREAD

**Issue by umdemir** [Soneso/stellar-ios-mac-sdk#25]
Payment operation's response is not getting parsed. This used to work, so there might something changed on Horizon APIs. Tested with 1.1.5. 

**Error description:**
>  HorizonRequestError: parsingResponseFailed : "The operation couldn’t be completed. (stellarsdk.XDRDecoder.Error error 6.)"

**User code:**
```
var memo: Memo

if let memoID = memoID {
    memo = Memo.id(memoID)
} else {
    memo = Memo.none
}

let paymentOperation = PaymentOperation(sourceAccount: keyPair, destination: try KeyPair(accountId: destinationAccountID), asset: asset, amount: amount)
let transaction = try Transaction(sourceAccount: accountResponse, operations: [paymentOperation], memo: memo, timeBounds: nil)
try transaction.sign(keyPair: keyPair, network: MPConfig.STELLAR_NETORK)
try StellarSDK(withHorizonUrl: MPConfig.URL_HORIZON).transactions.submitTransaction(transaction: transaction) { (transactionPostResponse) -> (Void) in
    
    switch transactionPostResponse {
//                    case .success(let submitTransactionResponse):
    case .success(_):
        fulfill(())
    case .failure(let horizonRequestError):
        reject(horizonRequestError)
    }
    
}
```

**Response:**
{
  "_links": {
    "transaction": {
      "href": "https://horizon-testnet.stellar.org/transactions/89e43763c72331af432fb3db241b723e82370e0802d4a17c5c32d6284a9124d2"
    }
  },
  "hash": "89e43763c72331af432fb3db241b723e82370e0802d4a17c5c32d6284a9124d2",
  "ledger": 10642164,
  "envelope_xdr": "AAAAAN1u4nbfMpcFr71wNt1ViTlk/hS59jD0pMcyXzm3pfBFAAAAZACdq+gAAAARAAAAAAAAAAAAAAABAAAAAQAAAADdbuJ23zKXBa+9cDbdVYk5ZP4UufYw9KTHMl85t6XwRQAAAAEAAAAAv3PZYYqz1lB5qjK5R7Kn7MyHfHTIYxjTLqqSYEtjQ7QAAAABT0cAAAAAAAB8CTr1M3808ueF/pik9o3XLuo85lEv/PQVDVgGdMxkxAAAAAABCGO3AAAAAAAAAAG3pfBFAAAAQOTIsPSPYGnyrvEwGfsLChKiddgrA3YOf8ayHZr4tCavUXLRHh3UgxG3ncoiqDIY7sFTME+5pt9gAoKwLb7WnQo=",
  "result_xdr": "AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAA=",
  "result_meta_xdr": "AAAAAQAAAAIAAAADAKJi9AAAAAAAAAAA3W7idt8ylwWvvXA23VWJOWT+FLn2MPSkxzJfObel8EUAAAAA2F1ihgCdq+gAAAAQAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAKJi9AAAAAAAAAAA3W7idt8ylwWvvXA23VWJOWT+FLn2MPSkxzJfObel8EUAAAAA2F1ihgCdq+gAAAARAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAABAAAAAMAomLmAAAAAQAAAAC/c9lhirPWUHmqMrlHsqfszId8dMhjGNMuqpJgS2NDtAAAAAFPRwAAAAAAAHwJOvUzfzTy54X+mKT2jdcu6jzmUS/89BUNWAZ0zGTEAAAAGuuJGGAG8FtZ07IAAAAAAAEAAAAAAAAAAAAAAAEAomL0AAAAAQAAAAC/c9lhirPWUHmqMrlHsqfszId8dMhjGNMuqpJgS2NDtAAAAAFPRwAAAAAAAHwJOvUzfzTy54X+mKT2jdcu6jzmUS/89BUNWAZ0zGTEAAAAGuyRfBcG8FtZ07IAAAAAAAEAAAAAAAAAAAAAAAMAomLmAAAAAQAAAADdbuJ23zKXBa+9cDbdVYk5ZP4UufYw9KTHMl85t6XwRQAAAAFPRwAAAAAAAHwJOvUzfzTy54X+mKT2jdcu6jzmUS/89BUNWAZ0zGTEAAAAEqAibDYCf30L25IAAAAAAAEAAAAAAAAAAAAAAAEAomL0AAAAAQAAAADdbuJ23zKXBa+9cDbdVYk5ZP4UufYw9KTHMl85t6XwRQAAAAFPRwAAAAAAAHwJOvUzfzTy54X+mKT2jdcu6jzmUS/89BUNWAZ0zGTEAAAAEp8aCH8Cf30L25IAAAAAAAEAAAAAAAAAAA=="
}

**Comment by umdemir** [comment]
Applied a temporary fix:
https://github.com/Soneso/stellar-ios-mac-sdk/pull/26

**Comment by jediyeti** [comment]
Hello! Still receiving **stellarsdk.XDRDecoder.Error error 6** on **1.4.0** version with applied changes (https://github.com/Soneso/stellar-ios-mac-sdk/pull/26). Are there any solutions?

**Comment by umdemir** [comment]
We've been working with my fork (from 1.1.5 + #26) and it's working. I didn't switch to 1.4.0 yet. I think they've addressed the issue with Protocol 10's implementation, not sure though.

**Comment by chelemen-razvan** [comment]
I cannot reproduce your issue, could you provide a specific sample code that reproduces the issue?

**Comment by jediyeti** [comment]
I am sending ChangeTrustOperation in Transaction. It executes fine on Stellar-testnet side, so trusts are changed. However, `StellarSDKLog.printHorizonRequestErrorMessage(tag: "error while transaction submit", horizonRequestError: horizonRequestError)` prints:
`error while transaction submit: Horizon request error of type request failed with message: The operation couldn’t be completed. (stellarsdk.XDRDecoder.Error error 6.)
`
and `horizonRequestError.localizedDescription` prints: 
`The operation couldn’t be completed. (stellarsdk.HorizonRequestError error 10.)
`
Transaction response:
[https://horizon-testnet.stellar.org/transactions/b0a9b941f1465e06196064efd4a9cf2afb9b449e2fe60546dea2846333ac7344](url)

**Comment by chelemen-razvan** [comment]
This should be fixed in 1.4.1

**Comment by Patrick7893** [comment]
Hello! Still have this issue in 1.4.2 build.
Here is the code snippet: 


              
                guard let assetCode = "BCH"
                guard let assetIsuuer = "GC7IKZ7WSQPY443TWBOM6TU63YED2ZLGMPANM63XNCD75VG7CILKSLCQ"
                guard let limit = 100.0
                
                guard let privateKey = "..."
                let seed = try Seed(secret: privateKey)
                let keyPair = KeyPair(seed: seed)
                let limitDecimal = Decimal(limit)
                
            
                let issuerPublicKey = try PublicKey.init(accountId: assetIsuuer)
                let issuerKeyPair = KeyPair(publicKey: issuerPublicKey)
                guard let asset = Asset(type: AssetType.ASSET_TYPE_CREDIT_ALPHANUM4, code: assetCode, issuer: issuerKeyPair) else { throw StellarSDKError.invalidData }
                print(keyPair.accountId);
                sdk.accounts.getAccountDetails(accountId: keyPair.accountId) { (response) -> (Void) in
                    switch response {
                    case .success(let accountResponse):
                        print("account sequence: \(accountResponse.sequenceNumber)")
                        NSLog("success get account details")
                        
                        do {
                            
                            let changeTrustOperation = ChangeTrustOperation(sourceAccount: keyPair, asset: asset, limit: limitDecimal)
                            let transaction = try Transaction(sourceAccount: accountResponse, operations: [changeTrustOperation], memo: Memo.none, timeBounds: nil)

                            try transaction.sign(keyPair: keyPair, network: Network.testnet)
                            try self.sdk.transactions.submitTransaction(transaction: transaction, response: { (response) -> (Void) in
                                switch response {
                                case .success(let horizonRequestSuccess):
                                    NSLog("\(horizonRequestSuccess)")
                                    result(NSDictionary(dictionary: ["result": NSNumber(booleanLiteral: true)]))
                                    
                                case .failure(let horizonRequestError):
                                    StellarSDKLog.printHorizonRequestErrorMessage(tag: "error while transaction submit", horizonRequestError: horizonRequestError)
                                    print(horizonRequestError.localizedDescription)
                                    if (horizonRequestError.localizedDescription.contains("(stellarsdk.HorizonRequestError error 10.)")) {
                                        do {
                                           try print(transaction.getTransactionHash(network: Network.testnet))
                                        }
                                        catch {
                                            
                                        }
                                        result(NSDictionary(dictionary: ["result": NSNumber(booleanLiteral: true)]))
                                    
                                    }
                                   
                                    result(NSDictionary(dictionary: ["errors": NSArray(array: [horizonRequestError.localizedDescription])]))
                            }
                                
                            })
                        }
                        catch {
                            result(NSDictionary(dictionary: ["errors": NSArray(array: ["Unknown TX error"])]))
                        }
                        
                    case .failure(let accountResponse):
                        print(accountResponse)
                        NSLog("fail get account details")
                        result(NSDictionary(dictionary: ["errors": NSArray(array: ["Error while getting account details"])]))
                    }
            
                }

And here is my logs:

`2018-09-18 11:20:03.918832+0300 Runner[16040:140351] flutter: 2587.0
account sequence: 47458203209826316
2018-09-18 11:20:03.965723+0300 Runner[16040:140338] success get account details
error while transaction submit: Horizon request error of type request failed with message: The operation couldn’t be completed. (stellarsdk.XDRDecoder.Error error 6.)
The operation couldn’t be completed. (stellarsdk.HorizonRequestError error 10.)
8c24a2d34b6c490504e570f515642916ffd2b13575cce1765f19be7c5bbbe277
2018-09-18 11:20:06.908002+0300 Runner[16040:140351] flutter: true`

**Comment by Patrick7893** [comment]
No, I think this code is correct, couse it executes on stellar side fine, and I see new asset in my balances.

**Comment by chelemen-razvan** [comment]
I parsed your response and it looks like this:

`TransactionResult
feeCharged: 100
result: [txFailed]
results: Array[1]
[0]: [opInner]
tr: [changeTrust]
changeTrustResult: [changeTrustSelfNotAllowed]`

**Comment by Patrick7893** [comment]
Can you tell me please which line of code snippet is incorrect? Because I run this code again on other account and result is the same: trust is changed and errors in logs are the same. Can you please try to run this code on testnet with this private key: "SD7SMSUOEIADZEWH2WXMS7DQY7HXCLBRFS2LJTID7A6JKMHGFSZUIMKH" with any random asset from stellar testnet? 
I really cant see any mistake on my side.

**Comment by chelemen-razvan** [comment]
Every asset on the stellar network has an account issuer (in your case GC7IKZ7WSQPY443TWBOM6TU63YED2ZLGMPANM63XNCD75VG7CILKSLCQ). That account does not have to make a change trust operation. Change trust operations are made by all other account that need to hold the asset issued by the issuer account. So in `ChangeTrustOperation ` the `sourceAccount ` must be different from the issuer account

**Comment by chelemen-razvan** [comment]
I run this code and it works as expected
`        let assetCode = "BCH"
        let assetIsuuer = "GC7IKZ7WSQPY443TWBOM6TU63YED2ZLGMPANM63XNCD75VG7CILKSLCQ"
        let limit = 100.0
        
        let privateKey = "SD7SMSUOEIADZEWH2WXMS7DQY7HXCLBRFS2LJTID7A6JKMHGFSZUIMKH"
        let seed = try! Seed(secret: privateKey)
        let keyPair = KeyPair(seed: seed)
        let limitDecimal = Decimal(limit)
        
        
        let issuerPublicKey = try! PublicKey.init(accountId: assetIsuuer)
        let issuerKeyPair = KeyPair(publicKey: issuerPublicKey)
        let asset = Asset(type: AssetType.ASSET_TYPE_CREDIT_ALPHANUM4, code: assetCode, issuer: issuerKeyPair)
        print(keyPair.accountId);
        sdk.accounts.getAccountDetails(accountId: keyPair.accountId) { (response) -> (Void) in
            switch response {
            case .success(let accountResponse):
                print("account sequence: \(accountResponse.sequenceNumber)")
                NSLog("success get account details")
                
                do {
                    
                    let changeTrustOperation = ChangeTrustOperation(sourceAccount: keyPair, asset: asset!, limit: limitDecimal)
                    let transaction = try Transaction(sourceAccount: accountResponse, operations: [changeTrustOperation], memo: Memo.none, timeBounds: nil)
                    
                    try transaction.sign(keyPair: keyPair, network: Network.testnet)
                    try self.sdk.transactions.submitTransaction(transaction: transaction, response: { (response) -> (Void) in
                        switch response {
                        case .success(let horizonRequestSuccess):
                            NSLog("\(horizonRequestSuccess)")
                        case .failure(let horizonRequestError):
                            StellarSDKLog.printHorizonRequestErrorMessage(tag: "error while transaction submit", horizonRequestError: horizonRequestError)
                            print(horizonRequestError.localizedDescription)
                            if (horizonRequestError.localizedDescription.contains("(stellarsdk.HorizonRequestError error 10.)")) {
                                do {
                                    try print(transaction.getTransactionHash(network: Network.testnet))
                                }
                                catch {
                                    
                                }
                            }
                        }
                    })
                }
                catch {
                }
            case .failure(let accountResponse):
                print(accountResponse)
                NSLog("fail get account details")
            }
        }`

**Comment by Patrick7893** [comment]
Do you mean you had a 
` case .success(let horizonRequestSuccess):
                        NSLog("\(horizonRequestSuccess)")`

?

**Comment by chelemen-razvan** [comment]
Yes
